name: ledgerx

channels:
    - default

dependencies:
    - requests
    # dev resources
    - pandas
    # test resources
    - pytest
    - pip
    - pip:
        - websockets
        - python-dotenv
        - Deprecated
        # dev resources
        - twine
        - ipdb
        - "--editable ."
        # testing resources
        - requests_mock
